SELECT 
    ANI_IN.ANIMAL_ID, ANI_IN.NAME
FROM 
    ANIMAL_INS AS ANI_IN
JOIN 
    ANIMAL_OUTS AS ANI_OUT
ON 
    ANI_IN.ANIMAL_ID = ANI_OUT.ANIMAL_ID
ORDER BY 
    DATEDIFF(ANI_OUT.DATETIME, ANI_IN.DATETIME) DESC
LIMIT 2;