-- 코드를 입력하세요
SELECT 
    C.CAR_ID,
     IF(SUM(IF (START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16", 1, 0)), "대여중", "대여 가능") AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY C.CAR_ID
ORDER BY
    CAR_ID DESC;