SELECT O.PRODUCT_ID, PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM
    FOOD_ORDER AS O JOIN (
        SELECT
            PRODUCT_ID,
            PRODUCT_NAME,
            SUM(PRICE) AS PRICE
        FROM
            FOOD_PRODUCT
        GROUP BY
            PRODUCT_ID
    ) AS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE
    DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC;