-- 코드를 입력하세요
-- USED_GOODS_BOARD 

SELECT USER_ID, NICKNAME, TOTAL_SALES 
FROM USED_GOODS_USER AS U, (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS G
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    ORDER BY TOTAL_SALES ASC
) AS SUB
WHERE U.USER_ID = SUB.WRITER_ID AND TOTAL_SALES >= 700000;
