-- 코드를 입력하세요
SELECT
    BOOK_ID,
    DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM
    BOOK AS B
WHERE
    YEAR(B.PUBLISHED_DATE) = 2021
    AND B.CATEGORY = '인문'
ORDER BY
    PUBLISHED_DATE ASC;